backend:
  name: git-gateway
  branch: master

media_folder: "src/uploads"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "text" # Used in routes, e.g., /admin/collections/blog
    label: "Text" # Used in the UI
    folder: "_data/text" # The path to the folder where the documents are stored
    extension: "json"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

    editor:
      preview: false

  - name: "gallery"
    label: "Gallery"
    folder: "_data/gallery"
    extension: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Lägenheten"
        name: "lagenheten"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
      - label: "Nerja"
        name: "nerja"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}

  - name: "available-dates"
    label: "Available Dates"
    folder: "_data/available-dates"
    extension: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Tider"
        name: "tider"
        widget: "list"
        fields:
          - {label: "Tider", name: "tider", widget: "tider"}

    editor:
      preview: false
