backend:
  name: git-gateway
  branch: master

media_folder: "src/uploads"
public_folder: "/uploads"
extension: "json"

collections:
  - name: "text" # Used in routes, e.g., /admin/collections/blog
    label: "Text" # Used in the UI
    folder: "_data/text" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

    editor:
      preview: false
